name       : liberation-fonts-ttf
version    : 2.1.0
release    : 6
source     :
    - https://github.com/liberationfonts/liberation-fonts/files/4178407/liberation-fonts-ttf-2.1.0.tar.gz : a55243d135229da4d0783a6f04ae058d3ab39c4eaeddff99afa5879877cb616c
license    : OFL-1.1
component  : desktop.font
summary    : Liberation Font Pack
description: |
    Liberation Font Pack
install    : |
    install -dm00755 $installdir/usr/share/fonts/Liberation/
    install -m00644 *.ttf $installdir/usr/share/fonts/Liberation/
