name       : liberation-fonts-ttf
version    : 2.00.4
release    : 4
source     :
    - https://github.com/liberationfonts/liberation-fonts/files/2579281/liberation-fonts-ttf-2.00.4.tar.gz : c40e95fc5e0ecb73d4be565ae2afc1114e2bc7dc5253e00ee92d8fd6cc4adf45
license    : SIL-1.1
component  : desktop.font
summary    : Liberation Font Pack
description: |
    Liberation Font Pack
install    : |
    rm TODO
    mkdir -p %installroot%/usr/share/fonts/Liberation/
    mv *.ttf %installroot%/usr/share/fonts/Liberation/
    mkdir -p %installroot%/usr/share/doc/liberation-fonts-ttf/
    mv * %installroot%/usr/share/doc/liberation-fonts-ttf/
