name       : liberation-fonts-ttf
version    : 2.1.1
release    : 7
source     :
    - https://github.com/liberationfonts/liberation-fonts/files/4743886/liberation-fonts-ttf-2.1.1.tar.gz : 8ee2c16fe0f055e60dd8375449aff72d25dd623b9cc6f24790ce9d2e91446fca
license    : OFL-1.1
component  : desktop.font
summary    : Liberation Font Pack
description: |
    The Liberation Fonts is a font family which aims at metric compatibility with Arial, Times New Roman, and Courier New.
install    : |
    install -dm00755 $installdir/usr/share/fonts/truetype/liberation
    install -m00644 *.ttf $installdir/usr/share/fonts/truetype/liberation
