name       : liberation-fonts-ttf
version    : 2.00.1
release    : 2
source     :
    - https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-ttf-2.00.1.tar.gz : 7890278a6cd17873c57d9cd785c2d230d9abdea837e96516019c5885dd271504
license    : SIL-1.1
summary    : Liberation Font Pack
description: |
    Liberation Font Pack
builddeps  :
setup      : |
build      : |
install    : |
    rm TODO
    mkdir -p %installroot%/usr/share/fonts/Liberation/
    mv *.ttf %installroot%/usr/share/fonts/Liberation/
    mkdir -p %installroot%/usr/share/doc/liberation-fonts-ttf/
    mv * %installroot%/usr/share/doc/liberation-fonts-ttf/
