name       : liberation-fonts-ttf
version    : 2.1.4
release    : 8
source     :
    - https://github.com/liberationfonts/liberation-fonts/files/6418984/liberation-fonts-ttf-2.1.4.tar.gz : 26f85412dd0aa9d061504a1cc8aaf0aa12a70710e8d47d8b65a1251757c1a5ef
homepage   : https://github.com/liberationfonts/liberation-fonts
license    : OFL-1.1
component  : desktop.font
summary    : Liberation Font Pack
description: |
    The Liberation Fonts is a font family which aims at metric compatibility with Arial, Times New Roman, and Courier New.
install    : |
    install -dm00755 $installdir/usr/share/fonts/truetype/liberation
    install -m00644 *.ttf $installdir/usr/share/fonts/truetype/liberation
